### PR TITLE
implement array_merge_recursive()

### PR DESCRIPTION
**Pull request by drdzyk**

### CODE REVIEW

**Comment by unserialize** [comment]
Can you please rebase this MR onto current master (to make it compilable for M1)?

**Comment by drdzyk** [comment]
> Can you please rebase this MR onto current master (to make it compilable for M1)?

done

**Review by DrDet — COMMENTED** [review]
It's strange, but this code
```
<?php

function demo() {
    $result = array_merge_recursive([0,1,2], [3,4]);
    print_r($result);
}

demo();
```
fails on gcc like this:
image

The same code with `array_merge` works. After extracting the const arrays to variables it works too

**Comment by drdzyk** [comment]
Yea, nice catch. It turns out that @kphp-pure-function tag solve this problem. Fixed.

**Review by DrDet — APPROVED** [review]

**Pull request merged**
